export const dashboardRecords = [
  {
    id: "d1a7c5b1-1",
    dailyAverage: [
      { id: "da-1-jan", month: "Jan", pending: 15, completed: 10, filed: 8 },
      { id: "da-1-feb", month: "Feb", pending: 18, completed: 12, filed: 10 },
      { id: "da-1-mar", month: "Mar", pending: 16, completed: 14, filed: 12 },
      { id: "da-1-apr", month: "Apr", pending: 20, completed: 15, filed: 14 },
      { id: "da-1-may", month: "May", pending: 17, completed: 13, filed: 11 },
    ],
    complainToFIRRatio: {
      id: "cf-1",
      labels: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6"],
      complaints: [100, 120, 150, 130, 110, 90],
      FIR: [80, 95, 120, 140, 130, 100],
      conversion: [80, 79, 80, 85, 90, 88],
    },
    inTimeCompletedComplaints: {
      id: "itc-1",
      percentage: 52,
      provinceAvg: 36,
      districtAvg: 45,
      rangeAvg: 52,
    },
    overdueComplaints: {
      id: "oc-1",
      percentage: 48,
      provinceAvg: 36,
      districtAvg: 45,
      rangeAvg: 52,
    },
    complaintToFIRs: {
      id: "ctf-1",
      percentage: 89,
      provinceAvg: 36,
      districtAvg: 45,
      rangeAvg: 52,
    },
    natureOfComplaintsBreakdown: [
      { id: "noc-1-1", type: "Rape", percentage: 12 },
      { id: "noc-1-2", type: "Dacoity", percentage: 12 },
      { id: "noc-1-3", type: "Car Theft", percentage: 12 },
      { id: "noc-1-4", type: "Kidnapped", percentage: 12 },
      { id: "noc-1-5", type: "Bike Theft", percentage: 12 },
      { id: "noc-1-6", type: "XYZ", percentage: 12 },
      { id: "noc-1-7", type: "Harassment", percentage: 12 },
      { id: "noc-1-8", type: "Laptop Theft", percentage: 12 },
      { id: "noc-1-9", type: "Physical Attack", percentage: 12 },
      { id: "noc-1-10", type: "Brawl", percentage: 12 },
    ],
    rapeCaseTopTrend: [
      { id: "rctt-1-jan", month: "Jan", complaints: 10, FIRs: 8 },
      { id: "rctt-1-feb", month: "Feb", complaints: 8, FIRs: 6 },
      { id: "rctt-1-mar", month: "Mar", complaints: 14, FIRs: 10 },
      { id: "rctt-1-apr", month: "Apr", complaints: 12, FIRs: 9 },
      { id: "rctt-1-may", month: "May", complaints: 6, FIRs: 5 },
      { id: "rctt-1-jun", month: "Jun", complaints: 4, FIRs: 3 },
    ],
    rankingOfComplaintManagement: {
      id: "rcm-1",
      score: 89,
      total: 344,
    },
  },

  {
    id: "d1a7c5b1-2",
    dailyAverage: [
      { id: "da-2-jan", month: "Jan", pending: 12, completed: 8, filed: 7 },
      { id: "da-2-feb", month: "Feb", pending: 15, completed: 10, filed: 9 },
      { id: "da-2-mar", month: "Mar", pending: 18, completed: 12, filed: 10 },
      { id: "da-2-apr", month: "Apr", pending: 14, completed: 9, filed: 8 },
      { id: "da-2-may", month: "May", pending: 16, completed: 11, filed: 9 },
    ],
    complainToFIRRatio: {
      id: "cf-2",
      labels: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6"],
      complaints: [90, 110, 140, 120, 105, 85],
      FIR: [75, 90, 110, 130, 125, 95],
      conversion: [82, 81, 78, 84, 88, 85],
    },
    inTimeCompletedComplaints: {
      id: "itc-2",
      percentage: 55,
      provinceAvg: 38,
      districtAvg: 46,
      rangeAvg: 53,
    },
    overdueComplaints: {
      id: "oc-2",
      percentage: 45,
      provinceAvg: 35,
      districtAvg: 44,
      rangeAvg: 51,
    },
    complaintToFIRs: {
      id: "ctf-2",
      percentage: 85,
      provinceAvg: 34,
      districtAvg: 44,
      rangeAvg: 50,
    },
    natureOfComplaintsBreakdown: [
      { id: "noc-2-1", type: "Rape", percentage: 12 },
      { id: "noc-2-2", type: "Dacoity", percentage: 12 },
      { id: "noc-2-3", type: "Car Theft", percentage: 12 },
      { id: "noc-2-4", type: "Kidnapped", percentage: 12 },
      { id: "noc-2-5", type: "Bike Theft", percentage: 12 },
      { id: "noc-2-6", type: "XYZ", percentage: 12 },
      { id: "noc-2-7", type: "Harassment", percentage: 12 },
      { id: "noc-2-8", type: "Laptop Theft", percentage: 12 },
      { id: "noc-2-9", type: "Physical Attack", percentage: 12 },
      { id: "noc-2-10", type: "Brawl", percentage: 12 },
    ],
    rapeCaseTopTrend: [
      { id: "rctt-2-jan", month: "Jan", complaints: 9, FIRs: 7 },
      { id: "rctt-2-feb", month: "Feb", complaints: 7, FIRs: 5 },
      { id: "rctt-2-mar", month: "Mar", complaints: 13, FIRs: 9 },
      { id: "rctt-2-apr", month: "Apr", complaints: 11, FIRs: 8 },
      { id: "rctt-2-may", month: "May", complaints: 5, FIRs: 4 },
      { id: "rctt-2-jun", month: "Jun", complaints: 3, FIRs: 2 },
    ],
    rankingOfComplaintManagement: {
      id: "rcm-2",
      score: 92,
      total: 344,
    },
  },

  {
    id: "d1a7c5b1-3",
    dailyAverage: [
      { id: "da-3-jan", month: "Jan", pending: 20, completed: 14, filed: 12 },
      { id: "da-3-feb", month: "Feb", pending: 19, completed: 15, filed: 13 },
      { id: "da-3-mar", month: "Mar", pending: 21, completed: 16, filed: 14 },
      { id: "da-3-apr", month: "Apr", pending: 22, completed: 17, filed: 15 },
      { id: "da-3-may", month: "May", pending: 18, completed: 14, filed: 13 },
    ],
    complainToFIRRatio: {
      id: "cf-3",
      labels: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6"],
      complaints: [110, 130, 160, 140, 120, 100],
      FIR: [85, 100, 125, 145, 135, 105],
      conversion: [81, 80, 82, 86, 89, 87],
    },
    inTimeCompletedComplaints: {
      id: "itc-3",
      percentage: 60,
      provinceAvg: 40,
      districtAvg: 48,
      rangeAvg: 54,
    },
    overdueComplaints: {
      id: "oc-3",
      percentage: 42,
      provinceAvg: 34,
      districtAvg: 43,
      rangeAvg: 50,
    },
    complaintToFIRs: {
      id: "ctf-3",
      percentage: 91,
      provinceAvg: 37,
      districtAvg: 46,
      rangeAvg: 53,
    },
    natureOfComplaintsBreakdown: [
      { id: "noc-3-1", type: "Rape", percentage: 12 },
      { id: "noc-3-2", type: "Dacoity", percentage: 12 },
      { id: "noc-3-3", type: "Car Theft", percentage: 12 },
      { id: "noc-3-4", type: "Kidnapped", percentage: 12 },
      { id: "noc-3-5", type: "Bike Theft", percentage: 12 },
      { id: "noc-3-6", type: "XYZ", percentage: 12 },
      { id: "noc-3-7", type: "Harassment", percentage: 12 },
      { id: "noc-3-8", type: "Laptop Theft", percentage: 12 },
      { id: "noc-3-9", type: "Physical Attack", percentage: 12 },
      { id: "noc-3-10", type: "Brawl", percentage: 12 },
    ],
    rapeCaseTopTrend: [
      { id: "rctt-3-jan", month: "Jan", complaints: 11, FIRs: 9 },
      { id: "rctt-3-feb", month: "Feb", complaints: 9, FIRs: 7 },
      { id: "rctt-3-mar", month: "Mar", complaints: 15, FIRs: 11 },
      { id: "rctt-3-apr", month: "Apr", complaints: 13, FIRs: 10 },
      { id: "rctt-3-may", month: "May", complaints: 7, FIRs: 6 },
      { id: "rctt-3-jun", month: "Jun", complaints: 5, FIRs: 4 },
    ],
    rankingOfComplaintManagement: {
      id: "rcm-3",
      score: 88,
      total: 344,
    },
  },
];
